"""
PR Creator — open a pull request on a user's GitHub repository.

This module wraps the GitHub REST API calls required to land an
auto-generated doc patch as a reviewable pull request. It intentionally
uses the contents API (rather than shelling out to git) so the logic is
safe to run from a Cloud Function, a test, or a CLI.

Typical flow:
    creator = GitHubPRCreator(token, "owner/repo")
    creator.ensure_branch("main", "docrot/fix-xyz")
    creator.update_file(
        path="docs/API.md",
        content=new_text,
        branch="docrot/fix-xyz",
        message="docrot: update signature in docs/API.md",
    )
    pr = creator.create_pull_request(
        base="main",
        head="docrot/fix-xyz",
        title="Docrot: update documentation for foo",
        body="Auto-generated by Docrot Detector.",
    )
    print(pr["html_url"])
"""

from __future__ import annotations

import base64
import re
import time
from dataclasses import dataclass
from typing import Any, Dict, Optional

import requests


API_ROOT = "https://api.github.com"
DEFAULT_TIMEOUT = 20
USER_AGENT = "docrot-detector"


class GitHubAPIError(RuntimeError):
    """Raised when the GitHub REST API returns an unexpected response."""

    def __init__(self, status_code: int, message: str, payload: Any = None):
        super().__init__(f"GitHub API error {status_code}: {message}")
        self.status_code = status_code
        self.payload = payload


@dataclass
class FileOnRef:
    """A file fetched from a branch or commit."""

    path: str
    content: str
    sha: str
    ref: str


# ---------------------------------------------------------------------------
# Branch / ref helpers
# ---------------------------------------------------------------------------


_BRANCH_SAFE = re.compile(r"[^A-Za-z0-9._/-]+")


def sanitize_branch_name(name: str) -> str:
    """Reduce arbitrary text to a git-safe ref name."""
    cleaned = _BRANCH_SAFE.sub("-", name).strip("-./")
    return cleaned or f"docrot-fix-{int(time.time())}"


def build_branch_name(flag_id: str, symbol: str) -> str:
    """
    Build a conventional branch name for a docrot-applied fix.

    Example: "docrot/fix-a1b2c3d4-format_user"
    """
    short_id = (flag_id or "fix")[:8]
    safe_symbol = sanitize_branch_name(symbol or "doc")
    return sanitize_branch_name(f"docrot/fix-{short_id}-{safe_symbol}")


# ---------------------------------------------------------------------------
# REST wrapper
# ---------------------------------------------------------------------------


class GitHubPRCreator:
    """Thin wrapper around GitHub's REST API for doc-patch PRs."""

    def __init__(
        self,
        token: str,
        repo_full_name: str,
        session: Optional[requests.Session] = None,
    ):
        if not token:
            raise ValueError("GitHub token is required to create pull requests.")
        if "/" not in repo_full_name:
            raise ValueError(
                "repo_full_name must be 'owner/repo', got: " + repr(repo_full_name)
            )
        self.token = token
        self.repo = repo_full_name
        self.session = session or requests.Session()

    # -- internal ---------------------------------------------------------

    def _headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": USER_AGENT,
        }

    def _request(
        self,
        method: str,
        path: str,
        *,
        json: Optional[Dict[str, Any]] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> requests.Response:
        url = f"{API_ROOT}{path}"
        resp = self.session.request(
            method=method,
            url=url,
            headers=self._headers(),
            json=json,
            params=params,
            timeout=DEFAULT_TIMEOUT,
        )
        return resp

    @staticmethod
    def _raise_for_status(resp: requests.Response, *, allow: Optional[set] = None) -> dict:
        allow = allow or set()
        if resp.status_code in allow:
            return resp.json() if resp.content else {}
        if 200 <= resp.status_code < 300:
            return resp.json() if resp.content else {}
        try:
            payload = resp.json()
            message = payload.get("message") or resp.text
        except ValueError:
            payload = None
            message = resp.text
        raise GitHubAPIError(resp.status_code, message, payload)

    # -- public -----------------------------------------------------------

    def get_default_branch(self) -> str:
        resp = self._request("GET", f"/repos/{self.repo}")
        data = self._raise_for_status(resp)
        return data.get("default_branch", "main")

    def get_ref_sha(self, branch: str) -> str:
        """Return the commit SHA at the tip of a branch."""
        resp = self._request("GET", f"/repos/{self.repo}/git/ref/heads/{branch}")
        data = self._raise_for_status(resp)
        return data["object"]["sha"]

    def branch_exists(self, branch: str) -> bool:
        resp = self._request("GET", f"/repos/{self.repo}/git/ref/heads/{branch}")
        if resp.status_code == 200:
            return True
        if resp.status_code == 404:
            return False
        self._raise_for_status(resp)
        return False

    def ensure_branch(self, base_branch: str, new_branch: str) -> None:
        """Create `new_branch` from `base_branch` if it does not exist yet."""
        if self.branch_exists(new_branch):
            return
        base_sha = self.get_ref_sha(base_branch)
        payload = {"ref": f"refs/heads/{new_branch}", "sha": base_sha}
        resp = self._request(
            "POST", f"/repos/{self.repo}/git/refs", json=payload
        )
        self._raise_for_status(resp)

    def get_file(self, path: str, ref: str) -> FileOnRef:
        """Fetch a file's current content and blob sha on a given ref."""
        resp = self._request(
            "GET",
            f"/repos/{self.repo}/contents/{path}",
            params={"ref": ref},
        )
        data = self._raise_for_status(resp)
        raw_content = data.get("content", "")
        encoding = data.get("encoding", "base64")
        if encoding == "base64":
            decoded = base64.b64decode(raw_content).decode("utf-8", errors="replace")
        else:
            decoded = raw_content
        return FileOnRef(
            path=data.get("path", path),
            content=decoded,
            sha=data["sha"],
            ref=ref,
        )

    def update_file(
        self,
        path: str,
        content: str,
        branch: str,
        message: str,
        *,
        expected_sha: Optional[str] = None,
    ) -> dict:
        """
        Replace the contents of `path` on `branch` with `content`.

        When `expected_sha` is None we fetch the current blob sha to satisfy
        GitHub's contents API (it requires the current sha for updates to
        guard against concurrent writes).
        """
        if expected_sha is None:
            current = self.get_file(path, branch)
            expected_sha = current.sha
        encoded = base64.b64encode(content.encode("utf-8")).decode("ascii")
        payload = {
            "message": message,
            "content": encoded,
            "branch": branch,
            "sha": expected_sha,
        }
        resp = self._request(
            "PUT",
            f"/repos/{self.repo}/contents/{path}",
            json=payload,
        )
        return self._raise_for_status(resp)

    def create_pull_request(
        self,
        base: str,
        head: str,
        title: str,
        body: str,
        *,
        draft: bool = False,
    ) -> dict:
        payload = {
            "title": title,
            "head": head,
            "base": base,
            "body": body,
            "draft": draft,
        }
        resp = self._request(
            "POST", f"/repos/{self.repo}/pulls", json=payload
        )
        return self._raise_for_status(resp)

    def find_open_pr(self, head_branch: str) -> Optional[dict]:
        """Return an existing open PR whose head matches the given branch."""
        owner = self.repo.split("/", 1)[0]
        resp = self._request(
            "GET",
            f"/repos/{self.repo}/pulls",
            params={"head": f"{owner}:{head_branch}", "state": "open"},
        )
        data = self._raise_for_status(resp)
        if isinstance(data, list) and data:
            return data[0]
        return None
